version: "3.7"
services:
  postgres_db_container:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: rootpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_db_data_container:/var/lib/postgresql/data

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db_container
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - 8080:8080

volumes:
  postgres_db_data_container:

  # commands: docker-compose -f postgre-sql-adminer.yml up -d
   # System : PostgreSQL
  # Server: postgres_db_container
  # Username: postgres
  # Password : rootpassword
  # http://localhost:8080/
